export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_REVIEW_ADD_REQUEST = "ORDER_REVIEW_ADD_REQUEST";
export const ORDER_REVIEW_ADD_SUCCESS = "ORDER_REVIEW_ADD_SUCCESS";
export const ORDER_REVIEW_ADD_FAIL = "ORDER_REVIEW_ADD_FAIL";
