export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const STORE_ORDER_LIST_REQUEST = "STORE_ORDER_LIST_REQUEST";
export const STORE_ORDER_LIST_SUCCESS = "STORE_ORDER_LIST_SUCCESS";
export const STORE_ORDER_LIST_FAIL = "STORE_ORDER_LIST_FAIL";

export const STORE_ORDER_UPDATE_REQUEST = "STORE_ORDER_UPDATE_REQUEST";
export const STORE_ORDER_UPDATE_SUCCESS = "STORE_ORDER_UPDATE_SUCCESS";
export const STORE_ORDER_UPDATE_FAIL = "STORE_ORDER_UPDATE_FAIL";

export const STORE_ORDER_SUMMARY_REQUEST = "STORE_ORDER_SUMMARY_REQUEST";
export const STORE_ORDER_SUMMARY_SUCCESS = "STORE_ORDER_SUMMARY_SUCCESS";
export const STORE_ORDER_SUMMARY_FAIL = "STORE_ORDER_SUMMARY_FAIL";

export const ORDER_REVIEW_ADD_REQUEST = "ORDER_REVIEW_ADD_REQUEST";
export const ORDER_REVIEW_ADD_SUCCESS = "ORDER_REVIEW_ADD_SUCCESS";
export const ORDER_REVIEW_ADD_FAIL = "ORDER_REVIEW_ADD_FAIL";
