export const RECENT_PRODUCT_REQUEST = "RECENT_PRODUCT_REQUEST";
export const RECENT_PRODUCT_SUCCESS = "RECENT_PRODUCT_SUCCESS";
export const RECENT_PRODUCT_FAIL = "RECENT_PRODUCT_FAIL";

export const POPULAR_IMAGE_REQUEST = "POPULAR_IMAGE_REQUEST";
export const POPULAR_PRODUCT_REQUEST = "POPULAR_PRODUCT_REQUEST";
export const POPULAR_PRODUCT_SUCCESS = "POPULAR_PRODUCT_SUCCESS";
export const POPULAR_PRODUCT_FAIL = "POPULAR_PRODUCT_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const USER_PRODUCT_LIST_REQUEST = "USER_PRODUCT_LIST_REQUEST";
export const USER_PRODUCT_LIST_SUCCESS = "USER_PRODUCT_LIST_SUCCESS";
export const USER_PRODUCT_LIST_FAIL = "USER_PRODUCT_LIST_FAIL";
