export const RECENT_PRODUCT_REQUEST = "RECENT_PRODUCT_REQUEST";
export const RECENT_PRODUCT_SUCCESS = "RECENT_PRODUCT_SUCCESS";
export const RECENT_PRODUCT_FAIL = "RECENT_PRODUCT_FAIL";

export const POPULAR_IMAGE_REQUEST = "POPULAR_IMAGE_REQUEST";
export const POPULAR_PRODUCT_REQUEST = "POPULAR_PRODUCT_REQUEST";
export const POPULAR_PRODUCT_SUCCESS = "POPULAR_PRODUCT_SUCCESS";
export const POPULAR_PRODUCT_FAIL = "POPULAR_PRODUCT_FAIL";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
